### ISSUE TITLE
Add a details page for recording records.

### ISSUE THREAD

**Issue by binyu1005** [arextest/arex#101]

**Comment by binyu1005** [comment]
![image](https://user-images.githubusercontent.com/23733811/233840672-3a84476e-ad05-4b7d-bc3b-e9a4f9b3e508.png)
![image](https://user-images.githubusercontent.com/23733811/233840767-5cf9c4f8-cd91-4222-ad20-b4444f90cd97.png)
We could view the recording details of the case through this link.
Finished.

**Comment by 1pone** [comment]
https://github.com/arextest/arex/pull/110/commits/0843137f6a4849a6e67094d355d7718a2d979e5c
