### ISSUE TITLE
Redeploy arex by docker compose, visit arex web failed, index page is refreshed cyclically

### ISSUE THREAD

**Issue by Marco-Zheng** [arextest/arex#117]
Use docker-compose redeploy arex, got error as blow
```
git clone https://github.com/arextest/deployments.git 
cd deployments
docker-compose up -d
```

## Current Behavior

<img width="775" alt="image" src="https://user-images.githubusercontent.com/52538259/232021476-02077acd-6547-40df-a2ed-f27b7f9dc8c6.png">

deployment running as normal
![image](https://user-images.githubusercontent.com/52538259/232022618-8618dd76-583e-40e5-8d23-26f4381d4ff4.png)

## Your Environment

* Spring boot version: 2.2.6.RELEASE
* Java Version: 1.8
* Arex Version: latest

**Comment by mr3** [comment]
transferred: https://github.com/arextest/arex/issues/117

**Comment by zhangtao25** [comment]
This should be caused by the incompatibility between the data struct localstorage on the front-end of the new version and the old version. We will fix it in the next version. The temporary fix method is to clear the localstorage.
