### ISSUE TITLE
May I ask if it is possible to automatically capture and generate JSON field paths and parameter variables returned by the previous interface for association dependency generation, and automatically generate association parameter variables to be passed into the next interface, all of which will be automated. Is it possible to manually associate if it is invalid?

### ISSUE THREAD

**Issue by cfy3133** [arextest/arex#131]
![gi2ngvmb2](https://user-images.githubusercontent.com/43978367/233758361-8ac3a05f-11b0-4152-a56c-5debb50d2e26.png)

**Comment by cfy3133** [comment]
其实有个开源平台做出来了，但是不是很精确，而且易用性不是很好，所以问下您这个平台是否能做，谢谢！
以下是开源平台做的(Actually, there is an open-source platform that has been developed, but it is not very precise and the usability is not very good. Therefore, I would like to ask if this platform can be developed. Thank you!
The following is done by the open source platform)
![image](https://user-images.githubusercontent.com/43978367/233965542-e34cce31-ad65-4819-9f69-75d838623913.png)

**Comment by binyu1005** [comment]
This requirement is not strongly related to our current main function of recording and playback, temporarily close this issue
