### ISSUE TITLE
feat: Optimize interfaces(operations) stop recording configuration

### ISSUE THREAD

**Issue by binyu1005** [arextest/arex#140]
The current interface stop configuration does not have a description. users are very confused

![image](https://user-images.githubusercontent.com/23733811/234486961-928ae314-e5db-4d64-bc73-37f2f68092c2.png)

**Comment by 1pone** [comment]
https://github.com/arextest/arex/pull/159/commits/98ab369d3bff39df616e983a7cc002e735123032
