### ISSUE TITLE
feat: Optimize the recording configuration page

### ISSUE THREAD

**Issue by binyu1005** [arextest/arex#147]
1. The list of machines where the agent is mounted needs to be displayed externally, no need to click the button again to display the details
2. ExclusionOperationSet needs to be selected or manually entered
3. There needs to be a place to store the global exclusionOperationList
   eg: "excludeServiceOperationSet": 
["/h2-console*",
"/api/CMSGetServer",
"/api/record*",
"/artemis-discovery-service*",
"/artemis-discovery-service/api/discovery/lookup.json",
"null.handle",
"/vi/health",
"*/vi/health",
"//vi/api/ctrip/markdown",
"//vi*",
"/vi*",
"*_operationInfo",
"/api",
"*/metadata",
"/arex*",
"/slb*",
"*_operationinfo",
"/metrics",
"/Support/json/reply/*"]

![image](https://user-images.githubusercontent.com/23733811/234879202-826acf01-039c-4256-bc56-bd0d6036b205.png)

**Comment by 1pone** [comment]
https://github.com/arextest/arex/pull/159
