### ISSUE TITLE
Increase timing ability - proposal 

### ISSUE THREAD

**Issue by MentosL** [arextest/arex#148]
### Background

Currently, arex has the ability to perform most of the interface playback, but there may be different interface request rules in business scenarios.
For example, if an HTTP interface request runs every morning and we record it for three days for playback, it will be played back three times at the same time. There may be unsupported situations in the business, and the playback here may differ from the expected results in the business

### Expected

There is a separate module that can support certain interfaces or intercepted requests, supporting the ability to replay custom rules. For example, interface A requests once an hour, can last three times or three days, and so on

**Comment by binyu1005** [comment]
We are planning to develop scheduled tasks, such as playback at a fixed time every day, and notify users of the playback results through callbacks.

**Comment by binyu1005** [comment]
You can follow these steps to set up a scheduled task.  https://github.com/arextest/arex/issues/401#issuecomment-1760968665
