### ISSUE TITLE
bug: Batch execution cases do not have return value of http status.

### ISSUE THREAD

**Issue by binyu1005** [arextest/arex#149]
## Description
Users cannot distinguish which cases are executed successfully or not.

## Screen shot
![image](https://user-images.githubusercontent.com/23733811/235043838-946ff984-615a-4a75-a6c9-d8feaddf5694.png)

**Comment by 1pone** [comment]
https://github.com/arextest/arex/pull/475/commits/8a8c9c4e140e8e3d2ba1e16bf3ebc04daecf38e3
