### ISSUE TITLE
bug: There will be a serialization problem while posting message with Number in request.

### ISSUE THREAD

**Issue by binyu1005** [arextest/arex#150]
## Description
In order to solve the problem of loss of accuracy of the request sent by the front end, a layer of packaging is made for the digital type when sending the request. However, there is no corresponding unlocking in the chrome plug-in. Causes an error in backend deserialization.

## Screenshot
![image](https://user-images.githubusercontent.com/23733811/235049343-f898af36-dd3b-47b6-8547-7829485b5b89.png)

![image](https://user-images.githubusercontent.com/23733811/235049308-589baa14-9e96-4a4c-b6cd-6a355bc9523c.png)

**Comment by zhangtao25** [comment]
https://github.com/arextest/arex/pull/151
