### ISSUE TITLE
bug:接口配置成忽略录制，实际不生效

### ISSUE THREAD

**Issue by blackjuly** [arextest/arex#152]
操作步骤：
在record -> advanced -> operation 选择 /heartbeat

![arex-bug](https://user-images.githubusercontent.com/22900807/235077603-01841d3f-4453-4fba-8020-211ae7e14f64.PNG)
实际日志打印出，heartbeat仍在保存
![打印日志](https://user-images.githubusercontent.com/22900807/235083971-2f9663b5-544c-4ecb-9fb0-3d6c876eba5c.PNG)

**Comment by blackjuly** [comment]
![8c4d1901f77478ec3995acfb8c66665](https://github.com/arextest/arex/assets/22900807/98696127-5352-44f5-9bc0-4f13e0a5623d)

![6bd8fd79323c6042cbabdfbbaec8206](https://github.com/arextest/arex/assets/22900807/4ed55dc8-6624-4377-9ed0-965bae1c2b0c)

没有和import.yaml 联动啊，感觉应该是这个导致不生效

**Comment by coryhh** [comment]
https://github.com/arextest/arex-report/pull/191

**Comment by coryhh** [comment]
use "/koala-finance/heartbeat" install of "/heartbeat"
