### ISSUE TITLE
bug: [schedule] The warm-up case needs to add 'arex-record-id' to request header

### ISSUE THREAD

**Issue by binyu1005** [arextest/arex#153]
## Description
If there is no 'arex-record-id' in request header, the request will be recorded as normal traffic, which will modify the user's data during playback, and will also make the final comparison result incorrect

## Code segment
https://github.com/arextest/arex-replay-schedule/blob/main/src/main/java/com/arextest/schedule/sender/impl/HttpServletReplaySender.java
``` java
    @Override
    public boolean activeRemoteService(ReplayActionCaseItem caseItem) {
        Map<String, String> headers = newHeadersIfEmpty(caseItem.requestHeaders());
        headers.put(CommonConstant.AREX_REPLAY_WARM_UP, Boolean.TRUE.toString());
        return doSend(caseItem.getParent(), caseItem, headers);
    }
```

**Comment by coryhh** [comment]
https://github.com/arextest/arex-replay-schedule/pull/69
