### ISSUE TITLE
bug: [Frontend] PUT method is not working.

### ISSUE THREAD

**Issue by binyu1005** [arextest/arex#154]
## Description
PUT method is not working in arex, but it's good in postman.

## Screen shots
arex
![image](https://user-images.githubusercontent.com/23733811/235107895-e1b69b2f-83fa-4c89-8da2-b448a8bb35bb.png)

postman
![image](https://user-images.githubusercontent.com/23733811/235108134-7ee8c045-c514-42a5-93ec-9fa0ea8d142c.png)

**Comment by zhangtao25** [comment]
Sending requests using the Chrome extensions cannot be completely the same as the Postman desktop.
