### ISSUE TITLE
feat: wish author to support the environment without AVX support

### ISSUE THREAD

**Issue by sandybrdige** [arextest/arex#158]
when I run the docker-compose command ,the mongodb container cannot start successfully. cause the mongo image version cannot match our environment.

docker container status:
![image](https://user-images.githubusercontent.com/44826909/236166897-211e2c11-5e2a-4767-930e-25bab58503f7.png)

docker logs：
WARNING: MongoDB 5.0+ requires a CPU with AVX support, and your current system does not appear to have that!
  see https://jira.mongodb.org/browse/SERVER-54407
  see also https://www.mongodb.com/community/forums/t/mongodb-5-0-cpu-intel-g4650-compatibility/116610/2
  see also https://github.com/docker-library/mongo/issues/485#issuecomment-891991814

docker logs：
![image](https://user-images.githubusercontent.com/44826909/236166598-54f0177b-44ec-4088-a25b-bad318d0fa12.png)

**Comment by binyu1005** [comment]
https://github.com/arextest/deployments/blob/dev/docker-compose-mongo4.4.21.yml

Downgrade the mongo version using the above docker-compose script
