### ISSUE TITLE
improvement: Optimize the pages of comparison configuration

### ISSUE THREAD

**Issue by binyu1005** [arextest/arex#199]
### Description
Existing comparison pages are more laborious to use, and it is not a good idea to display all interfaces on one page.

### Optimization point
- [ ] Select an operation first and then modify the corresponding configuration.
- [ ] Combine ignore & sort list pages into one page.
- [ ] The step of pasting the response message into the interface is not required

**Comment by 1pone** [comment]
https://github.com/arextest/arex/pull/302
