### ISSUE TITLE
Feat: The API in the replay report support to be searched by full path.

### ISSUE THREAD

**Issue by lijing-22** [arextest/arex#218]
## Current Behavior
Currently, for the sake of display convenience, only the last segment of the API is shown in the replay report. This can result in multiple APIs appearing the same in some cases, requiring manual cursor movement to select the desired API. This process can be time-consuming and tedious.
![image](https://github.com/arextest/arex/assets/118187476/3f64f176-c28e-4c49-ae91-ef218d8cd402)

## Expected Behavior
Support full path search for APIs in the replay report and allow users to quickly find the desired API by searching for the complete path. 
![03448f25a0a248bc57e85997c721ac6](https://github.com/arextest/arex/assets/118187476/bddb9004-972d-4de7-a169-3c185c306d76)

**Comment by 1pone** [comment]
https://github.com/arextest/arex/pull/261
