### ISSUE TITLE
Feat: Add prefix validation functionality in the target host.

### ISSUE THREAD

**Issue by lijing-22** [arextest/arex#220]
## Expected Behavior

We should validate the prefixes entered in the Target host to prevent users from mistakenly entering incorrect values.
 
![image](https://github.com/arextest/arex/assets/118187476/ee323c43-383e-4b1b-a2d1-e952169c8ca8)

**Comment by binyu1005** [comment]
We will record the address of the last execution of each task, so this requirement becomes unnecessary.

Close as not planed
