### ISSUE TITLE
feat: Quick comparsion mode in compare sdk

### ISSUE THREAD

**Issue by binyu1005** [arextest/arex#257]
### Description
In order to improve the comparison efficiency, a quick comparison mode is provided, and the subsequent comparison will be stopped as long as inconsistent nodes are encountered during the comparison process.

**Comment by QizhengMo** [comment]
https://github.com/arextest/arex-replay-schedule/pull/117

**Comment by coryhh** [comment]
https://github.com/arextest/arex-compare-sdk/pull/27

**Comment by QizhengMo** [comment]
https://github.com/arextest/arex/pull/243
