### ISSUE TITLE
feat: Add agentStatus interface

### ISSUE THREAD

**Issue by binyu1005** [arextest/arex#295]
### Description
This interface will return 2 fields, one field represents whether the agent of the machine needs to be started, and the other field is a timestamp representing the last update time of the configuration

Request:
{
   "appId":"string"
   "host":"xx.xx.xx.xx"
}

Response:
{
   "status": 1           // 1 represents WORKING;   2 represents SLEEPING
   "version": 1688697130513      // the last update time of configuration
}

**Comment by coryhh** [comment]
## backgroud

arex-web-api provides the interface "/load" to register application, register instance,  deliver configuration and manage instance. The management of instance includes the health status and worker machine election. The health control of the instance is to report the instance status by the agent requesting "/load" every 15 minutes, and delete the unreported instance through the ttl of the database

## problem

The user drops the machine within 15 minutes, while the machine was previously set to working. When the user republishes to the new machine, it needs to wait for the old machine to be deleted and the new machine to be elected as the working machine before recording can be performed.

## plan

- "/load" is responsible for application registration and configuration delivery
- The new Interface "A"  is responsible for instance registration、configuration version management and worker machine election.
  - [ ] transfer the code of "/load" which is about "instance" to the new interface
  - [ ] agent requesting the new interface every one minute, modify the ttl of the collection "instances" one minute
  - [ ] configuration version management. Use the configured update time as the version number. The configuration involves RecordServiceConfig and DynamicClass. The new interface needs to return a version number to identify whether the configuration is updated. the version can be ```the count of DynamicClass of appid + Math.max(RecordServiceConfig.dataChangeUpdateTime, DynamicClass.dataChangeUpdateTime)```

**Comment by coryhh** [comment]
https://github.com/arextest/arex-report/pull/222
https://github.com/arextest/arex-storage/pull/62
