### ISSUE TITLE
Feat: Icon changes for request methods should be consistent.

### ISSUE THREAD

**Issue by lijing-22** [arextest/arex#304]
1. When the user changes the request method, the method icon in the tab should change accordingly.
2. When the user changes the request method and save, the method icon in the sidebar should change accordingly.
![image](https://github.com/arextest/arex/assets/118187476/bab3ad43-f274-4349-aebd-18e665f30113)

**Comment by 1pone** [comment]
https://github.com/arextest/arex/pull/302/commits/40963841b74d6063c7774f3e0e2e0926360ca197
