### ISSUE TITLE
Bug: collection batch run

### ISSUE THREAD

**Issue by QizhengMo** [arextest/arex#315]
![image](https://github.com/arextest/arex/assets/54135657/9865916a-e410-4d8f-8950-c6bc59312d0b)
1. Can not select a collection of cases

![image](https://github.com/arextest/arex/assets/54135657/23a24c0a-b59c-4582-82db-5792cf812b42)
2. Can not send the selected cases

**Comment by 1pone** [comment]
https://github.com/arextest/arex/pull/334
