### ISSUE TITLE
现在很多平台都是通过nginx代理访问，建议录制回放时可以平台的nginx也可以进行测试

### ISSUE THREAD

**Issue by liuxiaojun319** [arextest/arex#319]
操作步骤：
在使用过程中，无法通过平台的nginx代理的统一端口进行回放用例，现在只能选择单个服务下的端口进行回放，
预期结果：
希望可以实现nginx统一调度，毕竟现在很多平台都是走的nginx代理

**Comment by QizhengMo** [comment]
您指的是这种代理方式吗
http://domain.com/service1    --> nginx    --> service1 ip/8080

如果是这种，那在service1回放页面，创建回放的时候host填写http://domain.com/service1就可以了

**Comment by binyu1005** [comment]
经过验证，通过nginx代理访问，回放是可以调通的。
