### ISSUE TITLE
feat: Support comparsion configuration for dependencies of Mock

### ISSUE THREAD

**Issue by binyu1005** [arextest/arex#321]
### Description
In order to control the comparison more finely, we need to support the comparison configuration of each mock

**Comment by QizhengMo** [comment]
https://github.com/arextest/arex-replay-schedule/pull/132

**Comment by QizhengMo** [comment]
https://github.com/arextest/arex-report/pull/219

**Comment by QizhengMo** [comment]
https://github.com/arextest/arex-report/pull/217

**Comment by QizhengMo** [comment]
https://github.com/arextest/arex/pull/302/files
