### ISSUE TITLE
feat:能根据用户去区分流量吗？

### ISSUE THREAD

**Issue by zhufengyan** [arextest/arex#330]
在使用平台录制流量时，录制和展示的是服务全部的流量，但是个人再使用时想只看属于自己属性或者标示的流量，然后将这些流量进行标记用例。

**Comment by mr3** [comment]
@zhufengyan 目前用例列表展示是按照`服务-接口`维度展示, 数据保存周期四天, 是滚动的.

请问 `自己属性或者表示` 你描述的是在录制时还是录制后进行这个操作?

**Comment by lijing-22** [comment]
@zhufengyan 最近社区支持了用tag区分录制到的流量，如果有使用需要的话请参考：[流量环境区分](https://doc.arextest.com/zh-Hans/docs/chapter3/Pre-setting#%E6%AD%A5%E9%AA%A4%E4%BA%8C%E6%B5%81%E9%87%8F%E7%8E%AF%E5%A2%83%E5%8C%BA%E5%88%86)

**Comment by binyu1005** [comment]
Supported after version 0.6.2.2
Doc: https://doc.arextest.com/docs/chapter3/Pre-setting#step2-distinguishing-traffic-by-environment
