### ISSUE TITLE
docs: How to deploy all the services individually from the command line

### ISSUE THREAD

**Issue by Totti0135** [arextest/arex#335]
公司环境无法通过Docker-Compose或者helm进行安装，需要通过命令行对每个服务单独部署，请问有没有相关说明文档

Due to the limitations of my company's environment, I can't install via Docker-Compose or helm, I need to deploy each service individually via commands. Is there any documentation on this?

**Comment by lijing-22** [comment]
可以参考一下：http://arextest.com/zh-Hans/docs/chapter1/Quick%20Installation#%E6%9C%8D%E5%8A%A1%E5%8D%95%E7%8B%AC%E9%83%A8%E7%BD%B2%E5%8F%8A%E9%9D%9E%E5%AE%B9%E5%99%A8%E5%8C%96%E5%AE%89%E8%A3%85

**Comment by Blissqiu** [comment]
能不能再细化一下，比如说哪个仓库对应的是什么组件，部署流程是什么？部署的前要条件是什么？

**Comment by lijing-22** [comment]
可以的，文档里我们尽快添加细节。

**Comment by lijing-22** [comment]
Please refer to: http://arextest.com/docs/chapter1/non-containerized/

**Comment by binyu1005** [comment]
You could also use docker save/load command to transfer images to server without network.
https://stackoverflow.com/questions/23935141/how-to-copy-docker-images-from-one-host-to-another-without-using-a-repository
