### ISSUE TITLE
Bug: Environment variables do not take effect immediately after they are created and saved

### ISSUE THREAD

**Issue by lijing-22** [arextest/arex#345]
After saving the environment variables, users need to switch to another environment and back to this environment for the changes to take effect.
![6E6FYU{O U~M9H~4 6$%7DG](https://github.com/arextest/arex/assets/118187476/f8605a4f-5d54-453f-8d81-09b45eccd77b)

**Comment by 1pone** [comment]
https://github.com/arextest/arex/pull/386/commits/5abc172242cfbf4ceb49b01c5838b1fc7b68af1b
