### ISSUE TITLE
feat: Hope to be able to view the recorded test cases

### ISSUE THREAD

**Issue by tomzhang-liang** [arextest/arex#346]
这样可以了解录制了哪些用例，可以清楚的知道自己回放了什么。并希望在未来可增加删除录制内容功能，这样可以减少数据库的数据量。

I hope to be able to view the recorded test cases. This will allow me to understand what cases were recorded, and I can know exactly what I replayed. And I hope that in the future, we can add the function of deleting the recorded content, so that we can reduce the amount of data in the database.

**Comment by lijing-22** [comment]
目前录制到的用例是可以查看的。可以参考：http://arextest.com/zh-Hans/docs/chapter3/Traffic%20Replay%20Test#%E6%9F%A5%E7%9C%8B%E5%BD%95%E5%88%B6%E8%AF%A6%E6%83%85
![image](https://github.com/arextest/arex/assets/118187476/9512ab77-b671-4dae-93c5-906d63863663)
删除功能后续会支持~

**Comment by binyu1005** [comment]
Duplicate issue: https://github.com/arextest/arex/issues/400
