### ISSUE TITLE
bug: The base64 string appears in the comparison on the page

### ISSUE THREAD

**Issue by coryhh** [arextest/arex#357]
The interface is not annotated with @ResponseBody, and the agent cannot obtain the serialized object. Uniformly use base64 storage stream
<img width="1984" alt="image" src="https://github.com/arextest/arex/assets/44330697/ed5a59a0-ac83-49cb-92bb-9ede2c48d9c1">

**Comment by binyu1005** [comment]
duplicate issue: https://github.com/arextest/arex/issues/305

**Comment by ZhitaoGan** [comment]
https://github.com/arextest/arex-replay-schedule/pull/157
