### ISSUE TITLE
bug: The total number of recorded quantities is inconsistent with the quantity in the details

### ISSUE THREAD

**Issue by binyu1005** [arextest/arex#376]
![FN)QA S%7Y)AQY641UB T%A](https://github.com/arextest/arex/assets/23733811/20a6d51e-975c-4c7c-8630-f1f5b2492a96)

**Comment by 1pone** [comment]
https://github.com/arextest/arex/pull/434/commits/a423bd3c1138fbcf10737c46ef5d6418671b5662
