### ISSUE TITLE
bug: Method of InetAddress.getLocalHost().getHostAddress responds slowly in mac os

### ISSUE THREAD

**Issue by binyu1005** [arextest/arex#388]
### Description
in LogUtils.java
``` java  @SneakyThrows
    public static void init() {
        MDC.put(APP_TYPE, AREX_WEB_API);
        MDC.put(IP, InetAddress.getLocalHost().getHostAddress());
    }
```
InetAddress.getLocalHost().getHostAddress responds slowly in mac os
### Solution
we should get this value only once and cache it.

**Comment by mr3** [comment]
@binyu1005 Refer to: [NetUtils.java](https://github.com/arextest/arex-agent-java/blob/main/arex-instrumentation-foundation/src/main/java/io/arex/foundation/util/NetUtils.java#L14C5-L16C6)
```java
public static String getIpAddress() {
    return NetworkInterfaceManager.INSTANCE.getLocalHostAddress();
}
```
