### ISSUE TITLE
feat: Hope to view the historical recording cases

### ISSUE THREAD

**Issue by dongyi0412** [arextest/arex#394]
录制数据只能查看当天录制数据，对于线上bug可能存在于之前录制的流量时，不能很好的回放复现。希望可以添加一个历史录制数据的页面。可以根据录制的值进行查询。

Currently, the recorded data can only be viewed for the day, and for some online bugs that may exist in previously recorded traffic can not be well reproduced by replay. I hope to add a page for historical recorded data and can be queried with the recorded value.

**Comment by wildeslam** [comment]
Currently the system supports viewing recorded data within four days.
<img width="1019" alt="image" src="https://github.com/arextest/arex/assets/35320326/4c339f8f-14c5-4567-a8b9-77699f634c22">

**Comment by QizhengMo** [comment]
https://github.com/arextest/arex-report/pull/180

Supported since 0.3.0
Please refer to http://arextest.com/docs/chapter1/quick-installation#upgrade for upgrade guide
