### ISSUE TITLE
feat: Hope to create a timed task to replay traffic

### ISSUE THREAD

**Issue by dongyi0412** [arextest/arex#395]
希望可以支持下创建定时任务回放流量。比如：创建定时任务每天早上10点回放指定日期的流量（或固定回放前一天的流量）

I hope that AREX can support to create a timed task to replay traffic. For example: create a timed task to replay the traffic of a specified date at 10:00 am every day (or replay the previous day's traffic)

**Comment by mr3** [comment]
@dongyi0412 感谢你的反馈，我们正在计划增加这个功能。

Thank you for posting in the AREX community! , we are planning to add this feature.

@binyu1005 @lijing-22 please follow up this issue.

**Comment by QizhengMo** [comment]
请参考
https://github.com/arextest/arex/issues/401
