### ISSUE TITLE
feat: Integration with git CI

### ISSUE THREAD

**Issue by BenjaminChang** [arextest/arex#396]
希望能够提供与git相关集成的说明，例如，服务指定分支打包触发回放任务，自动生成报告等

Hope that AREX can provide a description of the integration with git, e.g., service-specific branch packing to trigger replay, automatic report generation, etc.

**Comment by binyu1005** [comment]
You can use your own CI integration tool such as GitHub Actions to automatically trigger playback by calling AREX's webhook.
Doc: https://doc.arextest.com/docs/chapter3/Traffic%20Replay%20Test#scheduled-testing-task
