### ISSUE TITLE
Feat: Hope to do regression testing to the collections of saved recorded cases at regular intervals

### ISSUE THREAD

**Issue by Ellery1** [arextest/arex#401]
背景：
业务上有回归用例的需求，我现在已经配置好 agent 和 server，并且依赖于已有的录制回放能力，创建好了需要回归的集合

需求：
我希望
1. 每天定时执行一次这个集合
2. 把结果通过某种方式（比如企微/钉钉/邮箱）发给质量owner
这里的“结果”包括：
2.1 arex 视角：集合执行结果
2.2 业务层面：该集合包含10个case，我想知道哪些case失败了

需要支持三个功能：
1. 定时执行
2. 对执行集合的结果进行 case by case 的“和录制进行对比”
3. 对比结果通过指定途径发送到指定人员

或者是否有除了使用集合之外的其它手段，达到“对沉淀下来的用例定时执行并且获取结果”的方法呢？

-----------------------

Background:
I have a business requirement for regression test cases. I have configured the agent and services, and I have created a regression collection based on the existing recording and replay capabilities.

Requirement:
I want to:
1. execute this collection once a day at regular intervals
2. send the results to the quality owner in some way (e.g. enterprise micro/pinterest/email).
The "results" here include:
2.1 From AREX: the result of the collection execution.
2.2 From business: assuming that the collection contains 10 cases, I want to know which cases failed.

Three features need to be supported:
1. timed execution
2. compare to the recording cases "case by case".
3. the comparison result will be sent to the specified person via the specified route.

-----------------------

Or is there any other way to "execute and get the result of the deposited use cases" other than using collections?

**Comment by Ellery1** [comment]
请教下这个需求我们有计划支持么？

**Comment by binyu1005** [comment]
1. 通知：比如企微/钉钉/邮箱  该功能目前不会支持。但是我们后续会支持把plan的运行结果通过回调函数的方式通知用户的接口，你们可以通过回调自己实现具体的通知方式。
2. 定时任务：你们可以通过第三方Jenkins、corn tab来实现定时任务，我们下个版本会支持通过接口来触发回放。

**Comment by binyu1005** [comment]
> 请教下这个需求我们有计划支持么？
通知：比如企微/钉钉/邮箱 该功能目前不会支持。但是我们后续会支持把plan的运行结果通过回调函数的方式通知用户的接口，你们可以通过回调自己实现具体的通知方式。
定时任务：你们可以通过第三方Jenkins、corn tab来实现定时任务，我们下个版本会支持通过接口来触发回放。

**Comment by QizhengMo** [comment]
在即将发布的 0.6.0 版本中


1. 可以在 Arex 回放界面上点击创建回放，填入目标服务 host 之后会自动生成创建回放的接口调用链接（HTTP GET）
Case 的时间范围为调用时间点-24H
<img width="1049" alt="image" src="https://github.com/arextest/arex/assets/54135657/6014b696-85e7-4c88-93d5-c2ff3b96aa93">



2.  获取到创建回放的调用链接后，需要一个触发创建的介质
以 Linux 自带的 crontab 为例
2.1 创建名为 routine 的文件，写入0 5 * * *  /usr/bin/curl [第一步中复制的创建地址]
2.2 `crontab routine`  加载 2.1 中配置的定时任务
2.3 `crontab -l` 查看是否成功写入定时任务

注：其中 0 5 * * *  为标准 Linux cron 表达式

**Comment by QizhengMo** [comment]
回放结果的外部通知功能，后端已经实现，将在 0.6.0 中发布，但是前端尚未实现配置页面。
如需使用请参考https://github.com/arextest/arex-api/blob/4b73fbd5c5ac7b9fc12bb6a1a7cb4ee477a6f30c/arex-web-core/src/main/java/com/arextest/web/core/business/listener/planfinish/InformPlanFinishedListener.java
中的请求结构，在 SystemConfig 表中手动插入配置。

我们将会在配套的配置页面上线后更新使用教程。
