### ISSUE TITLE
When I select a case from the replay result and save it to a collection, the front-end refreshes very slowly after clicking "Save".

### ISSUE THREAD

**Issue by Ellery1** [arextest/arex#408]
这里面有两个问题：
1. 点击保存，前端没反应，要过几秒钟才会跳出“保存成功”的提示。麻烦看看性能是否需要优化下
![image](https://github.com/arextest/arex/assets/109015572/9f2b0ffa-4a23-47f4-9027-0b7c6cfe475b)

2. 在前端没反应的前提下，多次点击“保存”，会把同一个用例保存多次。保存的时候是否应该加个幂等判断？
![image](https://github.com/arextest/arex/assets/109015572/df70379f-1e01-49f8-a56c-462b617d3344)

There are two issues here:
1. When I click save, the front-end doesn't respond, and it takes a few seconds to the "Save Successful" message. Please check if the performance needs to be optimized.

2. Clicking "Save" multiple times when the front-end doesn't respond will save the same case multiple times. Should there be an idempotency judgment when saving?

**Comment by binyu1005** [comment]
1. We cannot reproduce the first issue. After verification, it is observed that the speed of persistence slows down significantly if the database is limited to a configuration of 2 cores and 2 GB. Perhaps you can increase the configuration of Arex installation to resolve this issue.
2. The second issue is expected, as we allow users to persist duplicate use cases. In some scenarios, users may make certain modifications to the same persisted use case, resulting in a completely new use case.
