### ISSUE TITLE
Feat: Hope to be able to customize the number of displayed cases on one page, maybe 100 cases.

### ISSUE THREAD

**Issue by Ellery1** [arextest/arex#410]
When I look at the replayed cases, there are a lot of failed cases, but only up to 5 are shown on one page, as shown below:

![image](https://github.com/arextest/arex/assets/109015572/8063cf49-0c5a-4f2a-9887-be5901dc450c)

Maybe we can increase the number of cases displayed here? For example, the user can choose whether to display 5 or 100 cases.

---

我在查看回放用例的时候，有很多失败的用例，但是一页最多只显示 5 条，如下图：
![image](https://github.com/arextest/arex/assets/109015572/8063cf49-0c5a-4f2a-9887-be5901dc450c)

请问可以在这里增加显示的用例条数吗？比如由用户来控制是显示 5条还是 100条。要不然上面这一大片空白闲着也是闲着...

**Comment by 1pone** [comment]
已修复，试一下最新代码或者镜像
https://github.com/arextest/arex/pull/323/commits/c5f060f5fe9e4b723a959c02d04b4465dfedef1f

**Comment by Ellery1** [comment]
yes it did be fixed in latest version, thanks
