### ISSUE TITLE
Feat: The process is too complicated when saving a case from the replay report.

### ISSUE THREAD

**Issue by Ellery1** [arextest/arex#412]
When I save the recorded cases to the **collection**, I need to: 

1. create a request in collection;
2. select the case to be saved and select the corresponding collection, request.

As shown below:
![image](https://github.com/arextest/arex/assets/109015572/6d450caf-9a47-41e0-b8ed-2da0b2dba328)

I hope:

No need to create a request in the collection in advance, just select the case in the replay report, and select the collection, then AREX can automatically check the URL and request method of the case. Then compare it with the request under the selected collection:
1. if there is no request using the same URL and request method with that case, then a new request will automatically be created with the request URL automatically filled and the the case will be saved under the new request.
2. if the request has been created before, then the case will be automatically saved under that request.

In this way, users don't need to switch pages between the "Collection" and the "Replay Report" so many times.

---

我从回放结果中想保存用例到集合中（固化），现在的步骤是：
1. 集合中创建请求
2. 选中用例，点击保存，再选中对应的请求路径
如下图所示
![image](https://github.com/arextest/arex/assets/109015572/6d450caf-9a47-41e0-b8ed-2da0b2dba328)

是否可以支持：
我不需要提前先在集合中创建好请求，在用例回放界面选中用例，点击保存的时候，选中文件夹，自动去检查用例的 URL 和 get/post，然后跟选中的集合文件夹路径下面的请求做对比：
1. 如果该用例对应的请求之前没有被保存过，则自动新建请求，并且自动填充请求url
2. 如果保存过，则自动保存到该请求下
这样可以省一些操作成本，避免在”集合“页面和”用例回放“页面切来切去的

**Comment by binyu1005** [comment]
We need to provide a new AddItemFromRecord interface that provides a default save path. The default path follows the rule of “appName/interfaceName/caseName”.

**Comment by zhangtao25** [comment]
https://github.com/arextest/arex/pull/496
