### ISSUE TITLE
【need for advise】server host auto reboot for lack of cpu resource by mongodb

### ISSUE THREAD

**Issue by Ellery1** [arextest/arex#416]
![image](https://github.com/arextest/arex/assets/109015572/6a250d20-6f33-45de-94e1-abdbbcf7c635)
我们发现mongodb太消耗server机器的资源了...

硬件：4C8G
软件：0.4.4
录制规模：18个应用约 30台 agent 开启 24 * 7 不间断录制，每分钟默认1条的录制频率

这样会导致 server 机器在资源被打满后自动重启，每天约发生重启 5~10 次。请教下官方对这个问题有什么建议吗？
比如如果是控制agent机器数量，那么降低到多少台机器为佳？或者是有其它什么解决思路？

**Comment by mr3** [comment]
@Ellery1 Agent启动建议应用单个集群默认启动一台

@binyu1005 请协助看看 mongodb 资源占用的问题

**Comment by binyu1005** [comment]
建议将写入mongo的日志等级调整到ERROR，来降低写日志占用的数据库连接资源
设置方案如下：
在docker-compose中的3个java项目中分别添加如下配置：
arex-web-api: -Dlogging.level.com.arextest=ERROR
storage: -Dlogging.level.com.arextest.storage=ERROR
schedule: -Dlogging.level.com.arextest.schedule=ERROR

**Comment by Ellery1** [comment]
> 建议将写入mongo的日志等级调整到ERROR，来降低写日志占用的数据库连接资源 设置方案如下： 在docker-compose中的3个java项目中分别添加如下配置： arex-web-api: -Dlogging.level.com.arextest=ERROR storage: -Dlogging.level.com.arextest.storage=ERROR schedule: -Dlogging.level.com.arextest.schedule=ERROR

按照你的建议我修改了配置，效果很好，最近几天都没发现有自动重启的现象了。这个 issue先关闭，感谢感谢~
