### ISSUE TITLE
feat: add 'tag' while recording

### ISSUE THREAD

**Issue by Ellery1** [arextest/arex#419]
背景：
1. 我们有多套测试环境，各个测试环境下的后台配置都不一样。用例能否通过，强依赖于后台配置
2. 多套环境中，我们都部署了 agent。录制的时候是不区分环境的，所有环境全部都录制下来了

遇到的问题：
回放的时候，只能通过 时间段 + 接口名 的方式来筛选回放用例，这样会导致我录制到的 环境A 中的数据，可能会回放到 环境B 中去

随之而来的茫茫多的case因为后台配置不match而失败...

请教下我有办法做到“在哪个环境录制的就在哪个环境回放”吗？

**Comment by lijing-22** [comment]
You can name the applications differently for different environments.

目前 AREX 还不支持，但是你可以对不同测试环境中的应用命名不同的名称，方便区分。

**Comment by Ellery1** [comment]
> 
"你可以对不同测试环境中的应用命名不同的名称"
--> 请教下这个要怎么做到呢？在启动参数中指定名字吗？

**Comment by binyu1005** [comment]
> > 
> 
> "你可以对不同测试环境中的应用命名不同的名称" --> 请教下这个要怎么做到呢？在启动参数中指定名字吗？

是的，可以在挂载agent的时候指定不同的arex.service.name来区分

**Comment by ddkwing** [comment]
请问这个能力后续有计划支持吗？我们是多环境多国家线的情况，同一个服务会有很多service，完全通过service name定义，服务多了之后会很难区分。

**Comment by lijing-22** [comment]
> 请问这个能力后续有计划支持吗？我们是多环境多国家线的情况，同一个服务会有很多service，完全通过service name定义，服务多了之后会很难区分。

@ddkwing 这个功能我们后续会有支持的，预计在下下个版本（2023.11）前完成开发。

**Comment by binyu1005** [comment]
Supported in version 0.6.2.
Docs: https://doc.arextest.com/docs/chapter3/Pre-setting#step2-distinguishing-traffic-by-environment
