### ISSUE TITLE
docs: How to build a front-end and back-end development environment locally

### ISSUE THREAD

**Issue by imath60** [arextest/arex#420]
本地环境信息：
1、硬件：MacBook Air M1芯片
2、操作系统：MacOS 13.4.1
3、IDE：IntelliJ IDEA 2023.2
遇到的问题：
希望在本地进行AREX主工程的前后端的二次开发，求前后端工程及依赖中间件的相关部署、配置、启动文档。参考：[[开发环境搭建 - MeterSphere 文档](https://metersphere.io/docs/v2.x/dev_manual/#22)](https://metersphere.io/docs/v2.x/dev_manual/#22)

**Comment by lijing-22** [comment]
Thanks for suggestion. We'll write the developer documentation to make it easier for developers to get involved.

**Comment by lijing-22** [comment]
@imath60 Hi, the Development Documentation is ready, please refer to: http://arextest.com/docs/category/development-documentation.
