### ISSUE TITLE
add cookie in header ,but it does not take effect

### ISSUE THREAD

**Issue by qing1215ler** [arextest/arex#444]
<img width="1021" alt="image" src="https://github.com/arextest/arex/assets/5227978/d68fbc09-3d11-48c1-b382-13d1d14eb3f6">

**Comment by lijing-22** [comment]
Hi, 添加参数后有点击 Save 保存吗，另外可以检查下你的 Chrome 插件版本是不是最新的 1.0.65

**Comment by qing1215ler** [comment]
@lijing-22 插件版本是1.0.65，浏览器是不是不允许设置cookie呀？

**Comment by qing1215ler** [comment]
<img width="728" alt="image" src="https://github.com/arextest/arex/assets/5227978/6fbb83fb-1de1-497b-91fe-e9f6cb5a5bb0">
为啥我部署完之后选择collection并不能看见Authorization这个tab呢，点击collection没有反应，我看文档里是有的，如下图
<img width="953" alt="image" src="https://github.com/arextest/arex/assets/5227978/0eafcddd-0502-4ea6-8059-54ef28778003">

**Comment by lijing-22** [comment]
Authorization 这一块实际上还没有支持（精力有限）

**Comment by zhangtao25** [comment]
> @lijing-22 插件版本是1.0.65，浏览器是不是不允许设置cookie呀？

我们以前是支持修改的cookie 的，但是这个修改是修改整个浏览器对应host的 cookie，对整个 host 有较大影响，并且在上架 chrome 插件时有诸多安全审核，所以废弃了在 chrome 端修改 cookie 的功能。
