### ISSUE TITLE
回放的 域名 加一个 白名单 判断

### ISSUE THREAD

**Issue by zhouxingfako** [arextest/arex#457]
我有100个现网域名， 现在挑5个录制，另外95个没有加agent代理【如果回放上去，会产生脏数据。】，现在白名单的意思是，只能会放到指定域名上。

**Comment by binyu1005** [comment]
The management of playback domain names is not our main function, the issue of environment isolation should be managed by the users themselves. In this regard, our tool is highly flexible and has no restrictions
