### ISSUE TITLE
Feat: There should be a "Mock" tab in the force-recorded case and in the debug page

### ISSUE THREAD

**Issue by lijing-22** [arextest/arex#463]
1. in the force-recorded case:
![1694676121048](https://github.com/arextest/arex/assets/118187476/87e978c8-a3aa-4658-bd54-fbd040d7ccb1)
2. in the debug page:
![1694676225513](https://github.com/arextest/arex/assets/118187476/39ef8a66-ee51-4268-bedd-af3ec2590daf)

**Comment by zhangtao25** [comment]
https://github.com/arextest/arex/pull/496
