### ISSUE TITLE
提个优化点:希望能规范下回放报告页的路径

### ISSUE THREAD

**Issue by 904085855** [arextest/arex#502]
我们背景是这样:我这边有个测试平台，提测时回调arex回放接口，拿到回放列表信息，然后有一列是详情，点击详情按钮可以跳转到arex对应的回放报告页面.但是目前是实现不了的。
如下图，目前有两个问题，一个是current和row这两个参数不好计算，第二个是如果把这个tab页关闭了，即使复制上面那个地址也没法跳转到对对应的回放报告页面，0.5.0.1版本是可以的，但是那个地址又太复杂了，希望可以简单点，比如appId/planId这种。
我觉得这个优化点还是很有必要的，如果需要对接其他平台，肯定需要跳转回arex看回放报告，因为整个搬过去太麻烦，而且你们也没有类似下载回放报告这种功能，所以只能是展示部分重要信息，然后有个详情按钮跳转到回放报告详情页
![image](https://github.com/arextest/arex/assets/63353770/4965340d-707b-4410-bdd5-aaf7f029be91)

**Comment by QizhengMo** [comment]
回放结果的回调函数调度功能将在近期发布
