### ISSUE TITLE
feat: 忽略、数据乱序建议支持Xml格式的报文

### ISSUE THREAD

**Issue by zane001** [arextest/arex#530]
如题，目前只支持Json格式的

**Comment by binyu1005** [comment]
目前没有计划支持xml格式的报文对比，但是可以通过自定义的插件将xml转换成json再进行对比配置。预计下个版本支持。

**Comment by coryhh** [comment]
The problem is the same as https://github.com/arextest/arex/issues/666
You can add conversion method "xml to json" in the plugin jar
