### ISSUE TITLE
回放支持整个节点忽略

### ISSUE THREAD

**Issue by ZHFlys** [arextest/arex#544]
现在是点了忽略没反应

**Comment by lijing-22** [comment]
可以截图发上来看看吗？
节点指的是字段吗

**Comment by ZHFlys** [comment]
![image](https://github.com/arextest/arex/assets/37203843/63d65a52-e584-476c-8ec5-f666d1136776)
就是这个回放结果 现在是对某一个结果json节点支持忽略 希望支持整个结果的忽略

**Comment by binyu1005** [comment]
Will be supported in version 0.6.3
