### ISSUE TITLE
希望固化用例时content-type能够兼容“application/json;charset=UTF-8”类型

### ISSUE THREAD

**Issue by liuxiaoer99** [arextest/arex#554]
问题描述：
    被测服务的接口headers中Content-Type为“application/json;charset=UTF-8”，使用arex工具，在回放页面回放该服务请求后将回放用例save到collection中。在collection处检查save后的接口信息(headers和body)，发现body为空(如截图所示)；点击send发送请求时，返回响应中提示缺少请求参数，在DevTools查看发送的请求时也没有包含请求参数(如截图所示)。
预期描述：
    希望固化用例时，可以兼容“application/json;charset=UTF-8”类型，即固化保存后的用例包含正确的请求参数，发送固化后的请求时能够请求成功。
备注：使用的arex版本是0.5.0，arex-agnet为0.3.8。(arex0.5.0之前的版本在Content-Type:application/json基础上做过兼容，不过目前现象还是不能成功)
![问题截图1](https://github.com/arextest/arex-agent-java/assets/133987222/fc97b976-7ab8-47d6-aeb3-7b161292ec33)
![问题截图2](https://github.com/arextest/arex-agent-java/assets/133987222/8f1f1a94-1f50-47c2-bc97-5b7d44562e46)

**Comment by binyu1005** [comment]
Supported in version 0.6.2
