### ISSUE TITLE
希望支持以文件夹形式对录制的流量分类管理（分支、版本或业务功能等），且回放支持按文件夹筛选流量

### ISSUE THREAD

**Issue by MaxZhou117** [arextest/arex#602]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by binyu1005** [comment]
Try configuring tags in the agent to solve the issue of traffic classification.
Doc: https://doc.arextest.com/docs/chapter3/Pre-setting#step2-distinguishing-traffic-by-environment
