### ISSUE TITLE
录制到的api支持搜索框

### ISSUE THREAD

**Issue by HumorChen** [arextest/arex#609]
录制到的api支持搜索框
![image-20240129202837793](https://chpic.oss-cn-shanghai.aliyuncs.com/202401292028231.png)

**Comment by lijing-22** [comment]
![image](https://github.com/arextest/arex/assets/118187476/4cddc227-ed23-491c-9dcd-e81ed33d0434)
搜索框在这里，可能有点隐秘，我们后续做明显点
