### ISSUE TITLE
通过的测试支持再次重新执行测试

### ISSUE THREAD

**Issue by HumorChen** [arextest/arex#610]
通过的测试支持再次重新执行测试

![image-20240129200032824](https://chpic.oss-cn-shanghai.aliyuncs.com/202401292004579.png)

**Comment by lijing-22** [comment]
@HumorChen 是出于什么样的需求呢，我们默认对回放成功的用例是不会再Rerun的。如果有需要可以点击 Run Test 重新开启一个report。

**Comment by HumorChen** [comment]
快速重新验证需要，开发同学可能临时改动一下，然后再看测试是否能过掉



---原始邮件---
发件人: "Jing ***@***.***&gt;
发送时间: 2024年1月30日(周二) 下午5:33
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [arextest/arex] 通过的测试支持再次重新执行测试 (Issue #610)




 
@HumorChen 是出于什么样的需求呢，我们默认对回放成功的用例是不会再Rerun的。如果有需要可以点击 Run Test 重新开启一个report。

**Comment by binyu1005** [comment]
您这种场景还是在新启动一个plan吧。我们的Rerun的定义就是失败重试。添加多重含义容易使大多数用户改到困惑。
