### ISSUE TITLE
录制的请求进Debug里的保存点了显示成功但没成功保存

### ISSUE THREAD

**Issue by HumorChen** [arextest/arex#611]
录制的请求进Debug里的保存点了显示成功但没成功保存
希望能成功保存到集合去
复现路径

![image-20240130173001196](https://chpic.oss-cn-shanghai.aliyuncs.com/202401301730381.png)
点Debug
![image-20240130173051457](https://chpic.oss-cn-shanghai.aliyuncs.com/202401301730478.png)
点保存提示成功，实际上没有保存
![image-20240130173205816](https://chpic.oss-cn-shanghai.aliyuncs.com/202401301732006.png)

**Comment by binyu1005** [comment]
Will be fixed in version 0.6.3
