### ISSUE TITLE
feat: test paths and Inclusion and exclusion rules for recording configurations can support fuzzy matching

### ISSUE THREAD

**Issue by MaxZhou117** [arextest/arex#614]

**Comment by lijing-22** [comment]
![image](https://github.com/arextest/arex/assets/118187476/82eb13d0-0682-4bb5-8b4f-907852ed8507)

![image](https://github.com/arextest/arex/assets/118187476/0ba6b536-e29f-4f4f-a1d1-7825b9e77640)
