### ISSUE TITLE
New Feature: Test case needs to inherit the URL and request parameters from the parent request

### ISSUE THREAD

**Issue by lijing-22** [arextest/arex#615]
Case should be able to inherit the url and request parameters from the parent request, and be editable so that subsequent url/parameter changes do not affect the parent request.

Request:
![image](https://github.com/arextest/arex/assets/118187476/8b529641-82a4-412e-8fbb-7db7fa68119c)

Case:
![image](https://github.com/arextest/arex/assets/118187476/4c7055d4-33e7-40e1-93fd-5e6fab6f16ca)

**Comment by binyu1005** [comment]
duplicated issue: https://github.com/arextest/arex/issues/637
