### ISSUE TITLE
New Feature: Request needs to be run in batches

### ISSUE THREAD

**Issue by lijing-22** [arextest/arex#616]
**Current**: The batch run can only select test **cases** created under the **Request**, which is too difficult for users to understand.
![image](https://github.com/arextest/arex/assets/118187476/91a26bac-762e-44df-bcc1-5b5b1080daf0)
Hopefully, for some requests that don't have a test case below, we can batch run them as well.

**Comment by 1pone** [comment]
fixed in https://github.com/arextest/arex/pull/625
