### ISSUE TITLE
Need to be able to customize the save path when saving recorded cases

### ISSUE THREAD

**Issue by lijing-22** [arextest/arex#619]
**Current**: When I want to save the recorded cases, it is forced to be saved under the fixed newly created Request and Collection, not good for extended use.
![image](https://github.com/arextest/arex/assets/118187476/cc68d54b-0688-490a-8499-057cf5686bc7)

Hopefully can additionally add a **Save as** function, then I can customize the save path.

**Comment by binyu1005** [comment]
Supported in version 0.6.3
