### ISSUE TITLE
When create the case in the request under the collection, the URL and Method of the case are empty and should be inherited from the request

### ISSUE THREAD

**Issue by HumorChen** [arextest/arex#621]
the URL and Method of the case should be inherited from the request.

![image-20240131150012799](https://chpic.oss-cn-shanghai.aliyuncs.com/202401311500926.png)

![image-20240131150118222](https://chpic.oss-cn-shanghai.aliyuncs.com/202401311501199.png)

**Comment by binyu1005** [comment]
Cannot reproduce. Please try again with the latest version 0.6.2.2
