### ISSUE TITLE
Collection功能里，新建了接口，接口新建样例的时候未继承URL等信息

### ISSUE THREAD

**Issue by HumorChen** [arextest/arex#637]
Collection功能里，新建了接口，接口新建样例的时候未继承URL等信息
![image-20240301110208589](https://chpic.oss-cn-shanghai.aliyuncs.com/202403011102115.png)
新建样例时，没有继承接口的信息
![image-20240301110306306](https://chpic.oss-cn-shanghai.aliyuncs.com/202403011103545.png)

**Comment by 1pone** [comment]
请问使用的是最新的v0.6.3么

**Comment by HumorChen** [comment]
使用的0.6.2版本，请问0.6.3版本支持是吗？

**Comment by 1pone** [comment]
是的，还有之前的一些issue在 0.6.3 版本中得到了修复，可以更新尝试一下

**Comment by HumorChen** [comment]
有了，谢谢
