### ISSUE TITLE
1、希望支持通过ldap登录2、加入权限功能，应用列表增删查改随着权限隔离

### ISSUE THREAD

**Issue by shenxingqi** [arextest/arex#641]
1、希望支持通过ldap登录【P0】
2、加入权限功能，应用列表增删查改随着权限隔离【P1】

**Comment by lijing-22** [comment]
@shenxingqi 你好，我们是有应用权限功能的，请参考：https://docs.arextest.com/zh-Hans/docs/chapter3/Customized-Configurations/Application-authentication

**Comment by binyu1005** [comment]
LDAP的登陆方式目前支持不了，用户可以二次开发自行支持。
