### ISSUE TITLE
希望DefaultRedisCacheProvider中支持哨兵模式的redis集群连接方式

### ISSUE THREAD

**Issue by hulahulaoye** [arextest/arex#645]
希望DefaultRedisCacheProvider中支持哨兵模式的redis集群连接方式，感谢

**Comment by coryhh** [comment]
已支持
应用启动参数配置，redis://masterName:password@{ip1}:{host1},{ip2}:{host2},{ip3}:{host3}/0
-Darex.redis.sentinelUrl=redis://masterName:password@192.168.0.1:6379,192.168.0.2:6379,192.168.0.3:6379/0
