### ISSUE TITLE
[Bug] 回放时部分api未通过测试，部分api回放结果invalid（404），将404接口放到exclude里并删除已录制的case后，再rerun测试会一直堵在rerunning状态不结束

### ISSUE THREAD

**Issue by HumorChen** [arextest/arex#656]
### Search before asking

- [X] I have searched the existing [issues](https://github.com/arextest/arex/issues) before asking.

### AREX Test Service

Schedule Service (arextest/arex-replay-schedule)

### Current Behavior

[Bug] 回放时部分api未通过测试，部分api回放结果invalid（404），将404接口放到exclude里并删除已录制的case后，再rerun测试会一直堵在rerunning状态不结束

### Expected Behavior

当发现被执行回放的case被删除应该报错提示样例已被删除，如果是因为加入到了exclude里也应该报错提示这个路径被排除了，而不能堵死在rerunning状态不流转下去。

### Steps To Reproduce

1. run test，部分测试样例返回的状态是invalid(异常是404)，没有通过录制
2. 将未通过测试的路径加入到exclude，将404异常的api的样例删除
3. 点击这个test的rerun

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

**Comment by wildeslam** [comment]
https://github.com/arextest/arex-replay-schedule/pull/300/files
