### ISSUE TITLE
[Feature] 回放结果对比时增加对先压缩后base64处理过的响应体的支持

### ISSUE THREAD

**Issue by nulinuli-nuli** [arextest/arex#666]
### Is there an existing issue for this?

- [X] I had searched in the [issues](https://github.com/arextest/arex-agent-java/issues) and found no similar issues.

### Are you willing to submit a pull request to implement this on your own?

- [ ] Yes I am willing to submit a pull request on my own!

**Comment by coryhh** [comment]
Arex supports the conversion function of comparison messages

- configure the URL of the extension jar package in the system configuration

<img width="1072" alt="image" src="https://github.com/arextest/arex/assets/44330697/0bc0a434-ca3f-4884-94f6-2b037a5641e8">

- choose the conversion method to use

<img width="1100" alt="image" src="https://github.com/arextest/arex/assets/44330697/577b0fa3-2710-4242-b22d-f76b8f93fb28">

For custom jar packages, please refer to the following link
https://github.com/arextest/arex-extension/tree/arex-compare-plugin

**Comment by coryhh** [comment]
The problem is the same as #666
You can add conversion method "xml to json" in the plugin jar
