### ISSUE TITLE
Clicking on a hyperlink<more detail> in the file<README.md> fails to open the page

### ISSUE THREAD

**Issue by imath60** [arextest/arex#7]
### Step1 : Click hyperlink<more detail>
![image](https://user-images.githubusercontent.com/6263682/180693340-ef0d435e-2ad8-48c0-8f6e-c73ce3e00c61.png)

### Actual Result： The link to the page is <[https://github.com/arextest/arex/blob/main/url](https://github.com/arextest/arex/blob/main/url)>
![image](https://user-images.githubusercontent.com/6263682/180692932-1111e8f9-76fc-4e69-b25b-892ae6e01121.png)

**Comment by haibing-wang** [comment]
Documentation will continue to be updated, this issue has been fixed
