### ISSUE TITLE
[Bug] 按照 DEV.md 执行 pnpm run build 报错

### ISSUE THREAD

**Issue by shichanglin5** [arextest/arex#703]
### Search before asking

- [X] I have searched the existing [issues](https://github.com/arextest/arex/issues) before asking.

### AREX Test Service

UI (arextest/arex)

### Current Behavior

按照 DEV.md 上的执行步骤：
```sh
git clone https://github.com/arextest/arex
cd arex
pnpm install
pnpm run dev
```

报错：
<img width="821" alt="image" src="https://github.com/user-attachments/assets/17c10ccf-9f0a-45ae-89c3-411f8f195891">

### Expected Behavior

执行成功

### Steps To Reproduce

1、clone 项目到本地
2、pnpm install & pnpm run build

### Anything else

pnpm version: 9.5.0
node version: 20.12.2

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

**Comment by shichanglin5** [comment]
pnpm9 会有这个问题

**Comment by zonewancheng** [comment]
pnpm9的一个默认配置变了
.npmrc文件增加配置即可
link-workspace-packages=true

**Comment by zonewancheng** [comment]
fix: https://github.com/arextest/arex/pull/708
