### ISSUE TITLE
[Bug] 生产环境录制，测试环境回放，生产环境的tag如何同步到测试环境？

### ISSUE THREAD

**Issue by yuanyinyan** [arextest/arex#711]
### Search before asking

- [X] I have searched the existing [issues](https://github.com/arextest/arex/issues) before asking.

### AREX Test Service

Storage Service (arextest/arex-storage)

### Current Behavior

生产环境录制，测试环境回放场景，需要同步生产环境数据到测试环境。
那么对于同一个App，两个环境tags不同，若不同步App数据，则回放时无法选择生产tag。若同步App数据，因为ObjectId不一样，同步后会有两条同名的App数据。

### Expected Behavior

希望有同步方案，可以在一个app中选择到生产环境和测试环境的tag。

### Steps To Reproduce

同步生产环境数据到测试环境，App数据如何同步

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

**Comment by 1pone** [comment]
release 0.6.5.2 已支持创建回放自定义 tag 名称
<img width="591" alt="image" src="https://github.com/user-attachments/assets/0fb456d7-35bf-4a98-b493-232789a7bdfa">
