### ISSUE TITLE
[Feature]希望 支持dubbo服务提供的rest 协议，目前会把注解为 @DubboService(protocol = "rest") 认为是dubbo rpc 接口导致回放失效

### ISSUE THREAD

**Issue by zjian95** [arextest/arex#724]
### Is there an existing issue for this?

- [X] I had searched in the [issues](https://github.com/arextest/arex-agent-java/issues) and found no similar issues.

### Are you willing to submit a pull request to implement this on your own?

- [ ] Yes I am willing to submit a pull request on my own!

**Comment by QizhengMo** [comment]
你好，经过调研，dubbo 官方现在将 rest 支持融合到 tripple 协议里了，并且推荐用户迁移到 triple 协议
https://cn.dubbo.apache.org/zh-cn/overview/mannual/java-sdk/reference-manual/protocol/overview/

我们暂不对旧的 rest 协议做单独支持
